title: Gangeshwari Rajavelu
logo: /assets/img/headshot_circle.png
city, state: San Francisco, California
email: gangeshwari.rajavelu@gmail.com
linkedIn: https://www.linkedin.com/in/gangeshwari-rajavelu-94991137/
linkedIn: [LinkedIn](https://www.linkedin.com/in/gangeshwari-rajavelu-94991137/)
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
